/// Generates the `@re-cinq/agent-contracts` TypeScript types from the annotated
/// `agentcore.crds` structs: introspects them with describe-d (the same model
/// `crdgen` reads to emit CRD YAML) and emits string-union types for the enums
/// and `interface`s for the structs. The CRDs are the source of truth; this keeps
/// the published TS contract glued to them so it cannot drift.
module tsgen;

import std.array : join;
import std.meta : AliasSeq;
import std.traits : isIntegral, isBoolean, isSomeString, isArray, isAssociativeArray,
	EnumMembers, ForeachType, ValueType;

import std.json : JSONValue;

import described : describe;

import agentcore.crds.schema : descriptionOf, jsonNameOf, isRequired;
import agentcore.crds.enums : PermissionMode, McpTransport, OutputFormat, SelectEvent,
	SelectRole, SinkType, ConcurrencyPolicy;
import agentcore.core.types : Phase;
import agentcore.crds.object_meta : ObjectMeta;
import agentcore.crds.env_var : EnvVar;
import agentcore.crds.secret_ref : SecretRef;
import agentcore.crds.mcp_server : McpServer;
import agentcore.crds.repo_ref : RepoRef;
import agentcore.crds.agent_resources : AgentResources;
import agentcore.crds.output_selector : OutputSelector;
import agentcore.crds.output_sink : OutputSink;
import agentcore.crds.output_spec : OutputSpec;
import agentcore.crds.agent_definition_spec : AgentDefinitionSpec;
import agentcore.crds.agent_definition : AgentDefinition;
import agentcore.crds.station_spec : StationSpec;
import agentcore.crds.station : Station;
import agentcore.crds.agent_spec : AgentSpec;
import agentcore.crds.agent_status : AgentStatus;
import agentcore.crds.agent : Agent;

/// The enums emitted as TypeScript string-union types, in declaration order.
private alias AllEnums = AliasSeq!(PermissionMode, McpTransport, OutputFormat,
	SelectEvent, SelectRole, SinkType, ConcurrencyPolicy, Phase);

/// The structs emitted as TypeScript interfaces (dependency-first for readability;
/// TS does not require forward declaration).
private alias AllStructs = AliasSeq!(ObjectMeta, EnvVar, SecretRef, McpServer, RepoRef,
	AgentResources, OutputSelector, OutputSink, OutputSpec,
	AgentDefinitionSpec, AgentDefinition, StationSpec, Station, AgentSpec, AgentStatus, Agent);

/// The TypeScript type expression for D type `FT`. Mirrors `crdgen.emitType`'s
/// dispatch: a `JSONValue` preserve-unknown object becomes `unknown`; an enum and a
/// struct reference the named type emitted for them; the scalars/array/map map to
/// their TS equivalents. `JSONValue` is matched before the generic `struct` arm
/// (it is itself a struct), and `string` before the generic `array` arm.
template tsType(FT)
{
	static if (is(FT == JSONValue))
		enum tsType = "unknown";
	else static if (is(FT == enum))
		enum tsType = FT.stringof;
	else static if (isIntegral!FT)
		enum tsType = "number";
	else static if (isBoolean!FT)
		enum tsType = "boolean";
	else static if (isSomeString!FT)
		enum tsType = "string";
	else static if (isAssociativeArray!FT)
		enum tsType = "Record<string, " ~ tsType!(ValueType!FT) ~ ">";
	else static if (isArray!FT)
		enum tsType = tsType!(ForeachType!FT) ~ "[]";
	else static if (is(FT == struct))
		enum tsType = FT.stringof;
	else
		static assert(false, "tsgen: unsupported field type " ~ FT.stringof);
}

/// `export type <Name> = "v1" | "v2";` from an enum's string values.
string emitEnum(E)()
{
	string[] values;
	static foreach (member; EnumMembers!E)
		values ~= "\"" ~ cast(string) member ~ "\"";
	return "export type " ~ E.stringof ~ " = " ~ values.join(" | ") ~ ";\n";
}

/// `export interface <Name> { ... }` from a struct's fields. Field optionality is
/// `@Required` → no `?`; wire names come from `@Json`; `@Description` becomes JSDoc.
string emitInterface(T)()
{
	string s;
	enum typeDesc = descriptionOf!T;
	static if (typeDesc.length)
		s ~= "/** " ~ typeDesc ~ " */\n";
	s ~= "export interface " ~ T.stringof ~ " {\n";
	enum aggregate = describe!T;
	static foreach (property; aggregate.properties)
	{{
		alias member = __traits(getMember, T, property.name);
		enum fieldDesc = descriptionOf!member;
		static if (fieldDesc.length)
			s ~= "  /** " ~ fieldDesc ~ " */\n";
		enum optional = isRequired!member ? "" : "?";
		s ~= "  " ~ jsonNameOf!member ~ optional ~ ": " ~ tsType!(typeof(member)) ~ ";\n";
	}}
	s ~= "}\n";
	return s;
}

/// The full generated TypeScript file: a do-not-edit banner, the enum unions, then
/// the interfaces.
string emitTypes()
{
	string s = "// Code generated by ai-agent-tsgen from the agentcore CRD structs. DO NOT EDIT.\n";
	s ~= "// Regenerate: dub run :tsgen -- emit <path>/types.generated.ts\n\n";
	static foreach (E; AllEnums)
		s ~= emitEnum!E();
	static foreach (T; AllStructs)
		s ~= "\n" ~ emitInterface!T();
	return s;
}

version (unittest) import fluent.asserts;

/// tsType maps each D type kind to its TS expression.
@safe unittest
{
	static assert(tsType!int == "number");
	static assert(tsType!bool == "boolean");
	static assert(tsType!string == "string");
	static assert(tsType!(string[]) == "string[]");
	static assert(tsType!(string[string]) == "Record<string, string>");
	static assert(tsType!JSONValue == "unknown");
	static assert(tsType!PermissionMode == "PermissionMode");
	static assert(tsType!AgentResources == "AgentResources");
	static assert(tsType!(EnvVar[]) == "EnvVar[]");
}

/// emitEnum renders the string values as a union in declaration order.
@safe unittest
{
	emitEnum!PermissionMode().should.equal("export type PermissionMode = \"auto\" | \"bypass\";\n");
	emitEnum!ConcurrencyPolicy().should.equal(
		"export type ConcurrencyPolicy = \"Allow\" | \"Forbid\" | \"Replace\";\n");
	emitEnum!Phase().should.equal(
		"export type Phase = \"Pending\" | \"Running\" | \"Succeeded\" | \"Failed\";\n");
}

/// emitInterface honours @Required (no `?`), @Json wire names, and @Description JSDoc.
@safe unittest
{
	emitInterface!SecretRef().should.equal(
		"export interface SecretRef {\n" ~
		"  /** Environment variable name to expose the secret as. */\n" ~
		"  name: string;\n" ~
		"  /** Allowlisted secret-store key. */\n" ~
		"  ref: string;\n" ~
		"}\n");
}

/// Optional fields get `?`; enum/struct/array/map fields reference the named types.
@safe unittest
{
	const iface = emitInterface!AgentDefinitionSpec();
	iface.should.contain("export interface AgentDefinitionSpec {");
	iface.should.contain("  permission_mode?: PermissionMode;\n");
	iface.should.contain("  allowed_tools?: string[];\n");
	iface.should.contain("  resources?: AgentResources;\n");
	iface.should.contain("  tool_config?: unknown;\n");
	iface.should.contain("  max_turns?: number;\n");
}

/// emitTypes carries the banner, every enum, and every resource interface.
unittest
{
	const out_ = emitTypes();
	out_.should.contain("DO NOT EDIT.");
	out_.should.contain("export type Phase =");
	out_.should.contain("export type SinkType =");
	out_.should.contain("export interface Agent {");
	out_.should.contain("export interface Station {");
	out_.should.contain("export interface AgentDefinition {");
	out_.should.contain("  spec?: AgentSpec;\n");
	out_.should.contain("  status?: AgentStatus;\n");
}
