// Code generated by ai-agent-tsgen from the agentcore CRD structs. DO NOT EDIT.
// Regenerate: dub run :tsgen -- emit <path>/types.generated.ts

export type PermissionMode = "auto" | "bypass";
export type McpTransport = "stdio" | "http" | "sse";
export type OutputFormat = "text" | "json" | "stream-json";
export type SelectEvent = "tool_call" | "message" | "tool_result" | "result" | "usage";
export type SelectRole = "assistant" | "user";
export type SinkType = "stdout" | "http" | "file";
export type ConcurrencyPolicy = "Allow" | "Forbid" | "Replace";
export type Phase = "Pending" | "Running" | "Succeeded" | "Failed";

export interface ObjectMeta {
  name?: string;
  generateName?: string;
  namespace?: string;
  uid?: string;
  resourceVersion?: string;
  labels?: Record<string, string>;
  annotations?: Record<string, string>;
}

export interface EnvVar {
  name: string;
  value: string;
}

export interface SecretRef {
  /** Environment variable name to expose the secret as. */
  name: string;
  /** Allowlisted secret-store key. */
  ref: string;
}

export interface McpServer {
  name: string;
  transport: McpTransport;
  command?: string;
  args?: string[];
  url?: string;
  headers_secret?: string;
}

export interface RepoRef {
  name: string;
  url: string;
  ref?: string;
  path?: string;
  token_secret?: string;
}

export interface AgentResources {
  env?: EnvVar[];
  secrets?: SecretRef[];
  mcp_servers?: McpServer[];
  repos?: RepoRef[];
}

export interface OutputSelector {
  event: SelectEvent;
  tool?: string;
  role?: SelectRole;
  contains?: string;
}

export interface OutputSink {
  type: SinkType;
  url?: string;
  headers_secret?: string;
  path?: string;
}

export interface OutputSpec {
  format?: OutputFormat;
  /** JSON Schema validating the result. */
  schema?: unknown;
  select?: OutputSelector[];
  sinks?: OutputSink[];
}

/** The reusable recipe for a coding agent task. */
export interface AgentDefinitionSpec {
  /** Human summary for operators. */
  description?: string;
  /** Model id (e.g. claude-sonnet-4-6). If omitted, the runtime default is used. */
  model?: string;
  /** Task template; {placeholder} tokens are filled from an Agent's parameters. */
  prompt?: string;
  allowed_tools?: string[];
  disallowed_tools?: string[];
  permission_mode?: PermissionMode;
  max_turns?: number;
  resources?: AgentResources;
  output?: OutputSpec;
  /** Raw passthrough for tool-specific knobs. */
  tool_config?: unknown;
}

export interface AgentDefinition {
  apiVersion?: string;
  kind?: string;
  metadata?: ObjectMeta;
  spec?: AgentDefinitionSpec;
}

/** The runtime template that pairs a recipe with a Pod template. */
export interface StationSpec {
  /** Name of the AgentDefinition this Station runs. */
  agentDefRef: string;
  /** Wall-clock limit per run; becomes the Job's activeDeadlineSeconds. */
  deadlineMinutes?: number;
  successfulRunsHistoryLimit?: number;
  failedRunsHistoryLimit?: number;
  /** Max Agents of this Station running at once; 0 is unlimited. A Pending Agent waits while at the limit. */
  maxConcurrentRuns?: number;
  /** At the limit: Allow queues (default), Forbid caps at one, Replace cancels the oldest run for the new one. */
  concurrencyPolicy?: ConcurrencyPolicy;
  /** Standard Kubernetes PodTemplateSpec; the container named "agent" is wired with the recipe. */
  template: unknown;
}

export interface Station {
  apiVersion?: string;
  kind?: string;
  metadata?: ObjectMeta;
  spec?: StationSpec;
}

/** One run of a recipe in a Station. */
export interface AgentSpec {
  /** The Station to run in (which selects the recipe). */
  stationRef: string;
  /** External id for correlation. */
  taskId?: string;
  /** GitHub repo in owner/name form. */
  targetRepo?: string;
  branch?: string;
  /** Per-run values; fill the prompt {placeholder} tokens and pass to the agent. */
  parameters?: Record<string, string>;
}

export interface AgentStatus {
  phase?: Phase;
  jobName?: string;
  /** RFC3339 timestamp when the run began. */
  startedAt?: string;
  /** RFC3339 timestamp when the run ended. */
  completedAt?: string;
  exitCode?: number;
  output?: string;
  failureReason?: string;
  prUrl?: string;
}

export interface Agent {
  apiVersion?: string;
  kind?: string;
  metadata?: ObjectMeta;
  spec?: AgentSpec;
  status?: AgentStatus;
}
